# Generated by Django 4.2.7 on 2023-11-26 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_son_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='users/profile_pic', verbose_name='Profil Resmi')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='users/cover_pic', verbose_name='Kapak Resmi')),
                ('adress_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres Satırı 1')),
                ('adress_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres Satırı 2')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ülke')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eyalet')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir')),
                ('pin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pin Kodu')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Enlem')),
                ('longitute', models.CharField(blank=True, max_length=20, null=True, verbose_name='Boylam')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kişi')),
            ],
        ),
    ]
