# Generated by Django 4.2.7 on 2024-01-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='adress_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='adress_2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='adress',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Adres Satırı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Vendor'), (2, 'müşteri')], null=True),
        ),
    ]
